name = "flxQTL"
uuid = "ede81e08-c6d8-4fe3-94c2-f928d9d678ed"
authors = ["Hyeonju Kim <hyeonjukm01@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
